### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by nwhitehorn** [sems-server/sems#156]
The monitoring etc. scripts included with sems are Python-2-only, which is now EOL. Most of the scripts are trivial, and 2to3 does a good job of converting them to work with Python 3.

**Comment by juha-h** [comment]
Nathan Whitehorn writes:

> The monitoring etc. scripts included with sems are Python-2-only,
> which is now EOL. Most of the scripts are trivial, and 2to3 does a
> good job of converting them to work with Python 3.

Please provide a pull requests of those you have converted.

**Comment by hecko** [comment]
I have forked the codebase from b0cd42b7bd3ea714d7f4ec2a1adc119abde8f2fb and migrated the code ( here https://github.com/sems-server/sems/compare/master...hecko:sems:python3-rhel7?expand=1 ) so that it compiles for me on the following environment (its a legacy env, but important to me):

```
CentOS 7
Python3.6 (default in the distro)
mysql-connector-c++-devel-9.1.0-1.el7.x86_64 from https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
some additional packages from EPEL
```

so this now compiles and installs cleanly including the IVR extension:

```
PYTHON_VERSION=3.6 USE_SPANDSP=1 make
PYTHON_VERSION=3.6 USE_SPANDSP=1 make install
```

I would very much appreciate any feedback before I try to create a PR.

**Comment by juha-h** [comment]
It would be good if you could test your code also on Debian which currently has Python 3.11.

**Comment by hecko** [comment]
I will create a Dockerfile with a debian 12 base and try to compile within the next 24 hours. Are there any specific steps I should do before I shall submit a PR? Like linting / specific documentation?

**Comment by hecko** [comment]
@juha-h  can you please help with this: https://github.com/sems-server/sems/issues/156#issuecomment-2507327878

Im unsure which grammar header file is being addressed here - is this the one from Python dev package? Since this file is not present in Debian 12 in any of the packages available in the distribution.

**Comment by hecko** [comment]
> hey! We also have an integration for automatic rpm build for CentOS 7 via spec file, probably we should make changes there too.
> 
> https://copr.fedorainfracloud.org/coprs/denysp/sems/



> Marcel Hecko writes:
> I will create a Dockerfile with a debian 12 base and try to compile within the next 24 hours. Are there any specific steps I should do before I shall submit a PR? Like linting / specific documentation?
> Unfortunately sems project does not have any automatic checks like lint or builds on different platforms.

Can you please create a new issue for this so maybe I can come back to this later? :)

**Comment by juha-h** [comment]
@hecko `gammar.h` exists in Debian 11 in [libpython3.9-dev](https://packages.debian.org/bullseye/libpython3.9-dev), but does not anymore exist in  `libpython3.11-dev`.  So the `ModPy.cpp` code wound need to modified.

**Comment by juha-h** [comment]
Looks like it would be a quite big task to support dsm mod_py when Python version is higher than 3.9.  I do not use that module myself.  If someone else does, please go ahead and provide a PR.

**Comment by hecko** [comment]
So, at the moment I can compile sems on rhel7,8,9 and debian11, 12 but only if I use python3. There is no easy way to make sems main branch python2 compatible because of the ModPy.cpp. It has not been changed for several years so I assume the ModPy.cpp was never intended to be compiled against Python2.
Im writing a quick test suite and will hopefully create a PR in a following few days.

**Comment by hecko** [comment]
This ticket is addressed in https://github.com/sems-server/sems/pull/208
